name: Deploy to Heroku

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker image
      run: docker build . --file WebApp/Jobsity.CodeChallenge.WebApp/Dockerfile --tag financialchat
      
    - name: Deploy to Heroku
      run: |
        docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
        docker tag financialchat registry.heroku.com/$HEROKU_APP_NAME/web
        docker push registry.heroku.com/$HEROKU_APP_NAME/web
        heroku container:release web -a $HEROKU_APP_NAME
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
